spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/notion
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always